#!/bin/sh

## PHP-FCGID wrapper script for virtual hosts
## This script allows us to customize the php environment on a
## per-vhost basis. By default all vhosts use the same php.ini
##
## New version for cloverfield
##
## Author: Chris Pappas <cpappas@hepcom.ca>
## Last Updated: 2011-04-11
## Version: 0.3
##
## Removed the PHP_FCGI_MAX_CHILDREN as it is reported to cause problems?

PHPRC=/etc/php5/cgi/
export PHPRC
export PHP_FCGI_MAX_REQUESTS=1000
#export PHP_FCGI_MAX_CHILDREN=8
exec /usr/lib/cgi-bin/php

